### PR TITLE
Added plugin wrapper for Cura 4.13.1

### LINKED ISSUE #6: Cura 4.0 support?
Since Cura introduced latest 4.0 version with improved plugin support, I think it's time to fix wood script for Cura 4.0.

### LINKED ISSUE #10: Cura 4.8 "install"
I tried to work through your instructions to get the script to function with Cura and cannot figure out how to see if it's installed and to find wherever it adds the setting. Any help would be appreciated if i'm missing something simple! Added the .py file to the plugins folder where my other extension plugins reside. Any tips to find the setting? What will i be looking for within the program to utilize this great script? Should it appear in that extensions drop down menu or somewhere else? 

thanks!

### PR DESCRIPTION
**Pull request by todd-herbert**
Resolves #6 and resolves #10

Restores in-cura support for the plugin with Cura's new scripting system.
(It's not pretty, but seems to work)

### CODE REVIEW

**Comment by todd-herbert** [comment]
Near instant for small models, but can take several minutes for larger print jobs. During this time the main Cura UI thread is unresponsive. Would be good to have at least some indication of progress. Cura doesn't allow scripts to import tkinter, however something may be possible using Cura's inbuild graphics framework, uranium. I will look into it.

**Comment by todd-herbert** [comment]
>something may be possible using Cura's inbuild graphics framework, uranium. I will look into it.

All the pieces of the puzzle seem to be there, and I've got it working in principle. Should have a new commit in the next few days

**Comment by todd-herbert** [comment]
> Near instant for small models, but can take several minutes for larger print jobs. During this time the main Cura UI thread is unresponsive. Would be good to have at least some indication of progress.

As of 5547335c2f0d1891b5ebf1d89828343cb59dbdfc, the plugin script now generates a nice tidy progress bar, implemented with Cura's inbuilt UI module, "Uranium". 
 
progress

**Comment by MoonCactus** [comment]
Hi Todd - sorry for being plain silent for the last two weeks (I am bootstrapping a new company with 15h+/day work) ;)
Do not feel like you're working for nothing : these commits are both welcomed and precious, so I would pretty well incorporate them in master in the next days (may be end of week) :+1:

**Comment by todd-herbert** [comment]
> Hi Todd - sorry for being plain silent for the last two weeks (I am bootstrapping a new company with 15h+/day work) ;) Do not feel like you're working for nothing : these commits are both welcomed and precious, so I would pretty well incorporate them in master in the next days (may be end of week) 👍

No apologies necessary! I hope this string of comments doesn't come across as impatient; rather I was worried that you might come across the initial commit before I had a chance to tidy it up, so wanted to keep you updated on the situation.

**Comment by todd-herbert** [comment]
No problem! It happened that I needed to use the script last week and found that the QT version needed to be updated for Cura 5, so decided to push the change here, just in case. The whole script is certainly not tidy; I'm no python coder, so I'd definitely be pleased to see it rewritten!

**Pull request merged**
